spring:
  session:
    store-type: none
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: "public"
    show-sql: true
  datasource:
    url: "jdbc:postgresql://${PG_HOST:localhost}:5432/auth_service_db"
    username: "${PG_USERNAME:auth-service}"
    password: "${PG_PASSWORD:auth-service}"
    driver-class-name: org.postgresql.Driver

project:
  authentication:
    login-url: "/sign-in.html"
    loginProcessUrl: '/authenticate'
    username-parameter-name: "email"
    password-parameter-name: "password"

logging:
  level:
    org.springframework.security: DEBUG
